config/routes.rb
Rails.application.routes.draw do
  resources :bookmark_categories
  resources :categories
  resources :bookmark_types
  resources :types
  resources :bookmarks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/bookmark_types_controller.rb
class BookmarkTypesController < ApplicationController
  before_action :set_bookmark_type, only: [:show, :edit, :update, :destroy]

  # GET /bookmark_types
  # GET /bookmark_types.json
  def index
    @bookmark_types = BookmarkType.all
    @bookmark_type_count = BookmarkType.group_type
  end

  # GET /bookmark_types/1
  # GET /bookmark_types/1.json
  def show
  end

  # GET /bookmark_types/new
  def new
    @bookmark_type = BookmarkType.new
  end

  # GET /bookmark_types/1/edit
  def edit
  end

  # POST /bookmark_types
  # POST /bookmark_types.json
  def create
    @bookmark_type = BookmarkType.new(bookmark_type_params)

    respond_to do |format|
      if @bookmark_type.save
        format.html { redirect_to @bookmark_type, notice: 'Bookmark type was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark_type }
      else
        format.html { render :new }
        format.json { render json: @bookmark_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmark_types/1
  # PATCH/PUT /bookmark_types/1.json
  def update
    respond_to do |format|
      if @bookmark_type.update(bookmark_type_params)
        format.html { redirect_to @bookmark_type, notice: 'Bookmark type was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark_type }
      else
        format.html { render :edit }
        format.json { render json: @bookmark_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmark_types/1
  # DELETE /bookmark_types/1.json
  def destroy
    @bookmark_type.destroy
    respond_to do |format|
      format.html { redirect_to bookmark_types_url, notice: 'Bookmark type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark_type
      @bookmark_type = BookmarkType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_type_params
      params.require(:bookmark_type).permit(:bookmark_id, :type_id)
    end
end

app/helpers/bookmark_types_helper.rb
module BookmarkTypesHelper
end

app/views/bookmark_types/_form.html.erb
<%= form_with(model: bookmark_type, local: true) do |form| %>
  <% if bookmark_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark_type.errors.count, "error") %> prohibited this bookmark_type from being saved:</h2>

      <ul>
        <% bookmark_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bookmark_id %>
    <%= form.text_field :bookmark_id %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.text_field :type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmark_types/edit.html.erb
<h1>Editing Bookmark Type</h1>

<%= render 'form', bookmark_type: @bookmark_type %>

<%= link_to 'Show', @bookmark_type %> |
<%= link_to 'Back', bookmark_types_path %>

app/views/bookmark_types/index.html.erb
<p id="notice"><%= notice %></p>
 

<h1>Bookmark_Types</h1>

 <br>
  
<div>
<h2> Bookmarks by Type </h2>
<%= pie_chart @bookmark_type_count %>
</div>


<table>
  <thead>
    <tr>
      <th>Bookmark_id</th>
      <th>Bookmark</th>
      <th>Type_id</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmark_types.each do |bookmark_type| %>
      <tr>
        <td><%= bookmark_type.bookmark_id %></td>
        <td><%= bookmark_type.bookmark.name %></td>
        <td><%= bookmark_type.type_id %></td>
        <td><%= bookmark_type.type.name %></td>
        <td><%= link_to 'Show', bookmark_type %></td>
        <td><%= link_to 'Edit', edit_bookmark_type_path(bookmark_type) %></td>
        <td><%= link_to 'Destroy', bookmark_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark Type', new_bookmark_type_path %>

app/views/bookmark_types/new.html.erb
<h1>New Bookmark Type</h1>

<%= render 'form', bookmark_type: @bookmark_type %>

<%= link_to 'Back', bookmark_types_path %>

app/views/bookmark_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bookmark:</strong>
  <%= @bookmark_type.bookmark_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @bookmark_type.type_id %>
</p>

<%= link_to 'Edit', edit_bookmark_type_path(@bookmark_type) %> |
<%= link_to 'Back', bookmark_types_path %>