config/routes.rb
Rails.application.routes.draw do
  resources :bookmark_categories
  resources :categories
  resources :bookmark_types
  resources :types
  resources :bookmarks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bookmark_category.rb
class BookmarkCategory < ApplicationRecord
  belongs_to :bookmark
  belongs_to :category
end

app/controllers/bookmark_categories_controller.rb
class BookmarkCategoriesController < ApplicationController
  before_action :set_bookmark_category, only: [:show, :edit, :update, :destroy]

  # GET /bookmark_categories
  # GET /bookmark_categories.json
  def index
    @bookmark_categories = BookmarkCategory.all
  end

  # GET /bookmark_categories/1
  # GET /bookmark_categories/1.json
  def show
  end

  # GET /bookmark_categories/new
  def new
    @bookmark_category = BookmarkCategory.new
  end

  # GET /bookmark_categories/1/edit
  def edit
  end

  # POST /bookmark_categories
  # POST /bookmark_categories.json
  def create
    @bookmark_category = BookmarkCategory.new(bookmark_category_params)

    respond_to do |format|
      if @bookmark_category.save
        format.html { redirect_to @bookmark_category, notice: 'Bookmark category was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark_category }
      else
        format.html { render :new }
        format.json { render json: @bookmark_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmark_categories/1
  # PATCH/PUT /bookmark_categories/1.json
  def update
    respond_to do |format|
      if @bookmark_category.update(bookmark_category_params)
        format.html { redirect_to @bookmark_category, notice: 'Bookmark category was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark_category }
      else
        format.html { render :edit }
        format.json { render json: @bookmark_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmark_categories/1
  # DELETE /bookmark_categories/1.json
  def destroy
    @bookmark_category.destroy
    respond_to do |format|
      format.html { redirect_to bookmark_categories_url, notice: 'Bookmark category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark_category
      @bookmark_category = BookmarkCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_category_params
      params.require(:bookmark_category).permit(:bookmark_id, :category_id)
    end
end

app/helpers/bookmark_categories_helper.rb
module BookmarkCategoriesHelper
end

app/views/bookmark_categories/_form.html.erb
<%= form_with(model: bookmark_category, local: true) do |form| %>
  <% if bookmark_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark_category.errors.count, "error") %> prohibited this bookmark_category from being saved:</h2>

      <ul>
        <% bookmark_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bookmark_id %>
    <%= form.text_field :bookmark_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmark_categories/edit.html.erb
<h1>Editing Bookmark Category</h1>

<%= render 'form', bookmark_category: @bookmark_category %>

<%= link_to 'Show', @bookmark_category %> |
<%= link_to 'Back', bookmark_categories_path %>

app/views/bookmark_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmark_Categories</h1>

<table>
  <thead>
    <tr>
      <th>Bookmark_id</th>
      <th>Bookmark</th>
      <th>Category_id</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmark_categories.each do |bookmark_category| %>
      <tr>
        <td><%= bookmark_category.bookmark_id %></td>
        <td><%= bookmark_category.bookmark.name %></td>
        <td><%= bookmark_category.category_id %></td>
        <td><%= bookmark_category.category.name %></td>
        
        <td><%= link_to 'Show', bookmark_category %></td>
        <td><%= link_to 'Edit', edit_bookmark_category_path(bookmark_category) %></td>
        <td><%= link_to 'Destroy', bookmark_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark Category', new_bookmark_category_path %>

app/views/bookmark_categories/new.html.erb
<h1>New Bookmark Category</h1>

<%= render 'form', bookmark_category: @bookmark_category %>

<%= link_to 'Back', bookmark_categories_path %>

app/views/bookmark_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bookmark:</strong>
  <%= @bookmark_category.bookmark_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bookmark_category.category_id %>
</p>

<%= link_to 'Edit', edit_bookmark_category_path(@bookmark_category) %> |
<%= link_to 'Back', bookmark_categories_path %>